// Auto-generated by wrangler types / manually maintained
// Run "npx wrangler types" to regenerate from wrangler.json

interface Env {
  DB: D1Database;
  R2_BUCKET: R2Bucket;
  RESEND_API_KEY: string;
}
